spring.application.name=bramaLog

spring.data.mongodb.uri=mongodb://localhost:27017/BramaLogDB

server.port=8080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=firass.khlifa@gmail.com
spring.mail.password=wtiaadgphjumpbfu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# Spring Security OAuth2 Resource Server Configuration for JWT Validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/bramaLog
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8082/realms/bramaLog/protocol/openid-connect/certs

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
